---
title: "Tutorial 2: Model Comparison on Predicting Income Over $50K (Adult Censor Data)"
output: html_notebook
---

# 1. Frame Question & Specify Goal

## predictive v.s. descriptive

## Background info about the dataset (reference to tutorial 1)

Citation
Data source: https://archive.ics.uci.edu/ml/datasets/adult 
```{r}
## Load data and library
#library(tidyr)

tempTrain <- tempfile()
tempTest <- tempfile()
varNames <- c("age", "workclass","fnlwgt","education","education-num","marital-status","occupation","relationship","race","sex","capital-gain","capital-loss","hours-per-week","native-country", "income")
download.file("https://archive.ics.uci.edu/ml/machine-learning-databases/adult/adult.data",destfile=tempTrain, method="curl")
download.file("https://archive.ics.uci.edu/ml/machine-learning-databases/adult/adult.test",destfile=tempTest, method="curl")
raw_data_train <- read.csv(tempTrain, col.names = varNames)
raw_data_test <- read.csv(tempTest, col.names = varNames)
```


# 2. Cleaning

```{r}
## Generalize levels: (String manipulation)
# native country
# workclass
# education
# marital.status

## Missing values in: ("bin" values)
# native.country
# workclass
# capital.gain
# capital.loss
```

# 3.Variable plots
```{r}
## Multicollinearity (Feature engineering)
scatterplot.matrix(~age+workclass+education+marital.status | income, data=t[1:100,], main="Income")

# education v.s. education-num

# marital.status v.s. relationship
```

# 5.Model comparison
```{r} 
#(With cross validation)
## 5.1 Logistic Regression

## 5.2 Random forest

## 5.3 Neural Networks (Keras for Tensorflow)

## ...
```

# 6. Validation on test set
```{r}
## confusion matrix

## ROC

```

# 7. Discussion

